---

- name: Install required python-pycurl package
  hosts: docker
  gather_facts: no
  tasks:
    - name: Install pycurl
      apt: pkg=python-pycurl update_cache=yes cache_valid_time=600

- name: Install Docker
  hosts: docker
  sudo: yes
  roles:
    - angstwad.docker_ubuntu

- name: Install docker-enter command line utility
  hosts: docker
  sudo: yes
  tasks:
    - name: Install docker-enter
      command: docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter
